#!/system/xbin/bash
# Ahmad Khoirul Marzuqin
n="\033[0m" # Normal
# Ahmad Khoirul Marzuqin
c="\033[90m" # Coklat
# Ahmad Khoirul Marzuqin
m="\033[91m" # Merah
# Ahmad Khoirul Marzuqin
h="\033[92m" # Hijau
# Ahmad Khoirul Marzuqin
k="\033[93m" # Kuning
# Ahmad Khoirul Marzuqin
u="\033[94m" # Ungu
# Ahmad Khoirul Marzuqin
p="\033[95m" # Pink
# Ahmad Khoirul Marzuqin
b="\033[96m" # Biru
# Ahmad Khoirul Marzuqin
sh 0
# Ahmad Khoirul Marzuqin
echo "$u           ╔════════════════════════════╗
           ║$k Sms      :$h TIKET.COM$u       ║
           ║$k Maksimal :$h 1 x Per 5 Menit$u ║
           ╚════════════════════════════╝
$n"
# Ahmad Khoirul Marzuqin
echo -n "["$h">"$n"] Nomor Target :$k "
# Ahmad Khoirul Marzuqin
read irul
# Ahmad Khoirul Marzuqin
python2 dstc $irul
# Ahmad Khoirul Marzuqin
sh 1
# Ahmad Khoirul Marzuqin