#!/system/xbin/bash
clear
n="\033[0m" # Normal
c="\033[90m" # Coklat
m="\033[91m" # Merah
h="\033[92m" # Hijau
k="\033[93m" # Kuning
u="\033[94m" # Ungu
p="\033[95m" # Pink
b="\033[96m" # Biru
sh 0
echo "$u                    ╔══════════╗
                    ║$k Facebook$u ║
                    ╚══════════╝

╔══╗
║"$n"››"$u"║$b Menu Yang Tersedia :$u
║  ║
║"$n"00"$u"║$p (p)$m Edit Password List$u
║"$n"01"$u"║$b Id Grub Target$u
║"$n"02"$u"║$b Id Target$k 1$p (p)$u
║"$n"03"$u"║$b Id Target$k 2$p (p)$u
║"$n"04"$u"║$b Password Target$h 1$p (p)$u
║"$n"05"$u"║$b Password Target$h 2$p (p)$u
║"$n"09"$u"║$n Kembali$u
║  ║"
echo -n "║"$n"››"$u"║$b Pilih Nomor :$n "
read irul
echo $u"╚══╝$n"
termux-tts-speak $irul

# (p) Password List
if [ $irul = 00 ] || [ $irul = 0 ]
then
sh 0
echo "\033[0mUntuk Mengedit (p)
1. Ketik Password List Yang Anda Mau
2. Untuk Menyimpan Tekan Tombol CTRL +X > Y > Enter"
sleep 10;
nano p
sh irul
fi

# Facebook Id Grub Target
if [ $irul = 01 ] || [ $irul = 1 ]
then
sh igt
python2 igt_masuk
sh 2
fi

# Facebook Id Target
if [ $irul = 02 ] || [ $irul = 2 ]
then
sh it
python2 it_masuk
sh 2
fi

# Facebook Id Target Facebook Cracker v2
if [ $irul = 03 ] || [ $irul = 3 ]
then
sh it
python2 it_facebook_cracker_v2
sh 2
fi

# Facebook Password Target Mbf
if [ $irul = 04 ] || [ $irul = 4 ]
then
sh pt
python2 pt_mbf
sh 2
fi

# Facebook Password Target Mbf1
if [ $irul = 05 ] || [ $irul = 5 ]
then
sh pt
python2 pt_mbf1
sh 2
fi

# Kembali
if [ $irul = 09 ] || [ $irul = 9 ]
then
cd ..
sh irul
fi

termux-tts-speak Nomor Yang Anda Masukkan Salah
termux-tts-speak Silahkan Hubungi Pembuat Script Ini
sh irul