#!/system/xbin/bash
clear
n="\033[0m" # Normal
c="\033[90m" # Coklat
m="\033[91m" # Merah
h="\033[92m" # Hijau
k="\033[93m" # Kuning
u="\033[94m" # Ungu
p="\033[95m" # Pink
b="\033[96m" # Biru
sh 0
echo "$u                       ╔═════╗
                       ║$k Bot$u ║
                       ╚═════╝

╔══╗
║"$n"››"$u"║$b Menu Yang Tersedia :$u
║  ║
║"$n"0 "$u"║$n Download Aplikasi$u
║"$n"00"$u"║$c Edit Data Aplikasi$u
║"$n"01"$u"║$m Caping$u
║"$n"02"$u"║$h Cashtree$u
║"$n"03"$u"║$k KUBIK$u
║"$n"04"$u"║$p ToToNews$u
║"$n"05"$u"║$b VeeU$u
║"$n"06"$u"║$n YDNews$u
║"$n"09"$u"║$c Kembali$u
║  ║"
echo -n "║"$n"››"$u"║$b Pilih Nomor :$n "
read irul
echo $u"╚══╝$n"
termux-tts-speak $irul

# Download Aplikasi
if [ $irul = 0 ] || [ $irul = 0 ]
then
sh download
fi

# Edit
if [ $irul = 00 ] || [ $irul = 00 ]
then
sh edit
fi

# Bot Caping
if [ $irul = 01 ] || [ $irul = 1 ]
then
cd caping
php irul
cd ..
sh 1
fi

# Bot Cashtree
if [ $irul = 02 ] || [ $irul = 2 ]
then
sh 0
php c
sh 1
fi

# Bot KUBIK
if [ $irul = 03 ] || [ $irul = 3 ]
then
cd kubik
php irul
cd ..
sh 1
fi

# Bot ToToNews
if [ $irul = 04 ] || [ $irul = 4 ]
then
cd totonews
php irul
cd ..
sh 1
fi

# Bot VeeU
if [ $irul = 05 ] || [ $irul = 5 ]
then
cd veeu
php irul
cd ..
sh 1
fi

# Bot YDNews
if [ $irul = 06 ] || [ $irul = 6 ]
then
cd ydnews
php irul
cd ..
sh 1
fi

# Kembali
if [ $irul = 09 ] || [ $irul = 9 ]
then
cd ..
sh irul
fi

termux-tts-speak Nomor Yang Anda Masukkan Salah
termux-tts-speak Silahkan Hubungi Pembuat Script Ini
sh irul